services:

  db:
    image: mysql:8.0
    container_name: estacionamento-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: estacionamento
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build:
      context: ./
    container_name: estacionamento-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data:
