services:
  db:
    image: postgres:15-alpine
    container_name: estacionamento-db-pg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=estacionamento
    ports:
      - "5433:5432" # Mapeia a porta 5433 do seu PC para a 5432 do contêiner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d estacionamento"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build:
      context: ./
    container_name: estacionamento-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Variáveis para a conexão do banco de dados DENTRO do Docker
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
